apiVersion: v1
kind: Service
metadata:
  name: stooges
  labels:
    run: stooges
spec:
  ports:
  - port: 6001
    protocol: TCP
    name: curly
    nodePort: 32001
  - port: 6002
    protocol: TCP
    name: larry
    nodePort: 32002
  - port: 6001
    protocol: TCP
    name: moe
    nodePort: 32003
  selector:
    run: stooges
  type: NodePort
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: stooges
spec:
  replicas: 1
  template:
    metadata:
      labels:
        run: stooges
    spec:
      containers:

      - name: stooge-curly
        image: cdaringe/stooge
        ports:
        - containerPort: 6001
        env:
        - name: STOOGE
          value: curly

      - name: stooge-larry
        image: cdaringe/stooge
        ports:
        - containerPort: 6002
        env:
        - name: STOOGE
          value: larry

      - name: stooge-moe
        image: cdaringe/stooge
        ports:
        - containerPort: 6003
        env:
        - name: STOOGE
          value: moe
