apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: stooges
spec:
  replicas: 1
  template:
    metadata:
      labels:
        run: stooges
    spec:
      containers:

      - name: stooge-curly
        image: cdaringe/stooge
        ports:
        - containerPort: 6001
        env:
        - name: STOOGE
          value: curly

      - name: stooge-larry
        image: cdaringe/stooge
        ports:
        - containerPort: 6002
        env:
        - name: STOOGE
          value: larry

      - name: stooge-moe
        image: cdaringe/stooge
        ports:
        - containerPort: 6003
        env:
        - name: STOOGE
          value: moe
