apiVersion: v1
kind: Service
metadata:
  name: stooges
  labels:
    run: stooges
spec:
  ports:
  - port: 6001
    protocol: TCP
    name: curly
    nodePort: 32001
  - port: 6002
    protocol: TCP
    name: larry
    nodePort: 32002
  - port: 6001
    protocol: TCP
    name: moe
    nodePort: 32003
  selector:
    run: stooges
  type: NodePort
