apiVersion: v1
kind: Service
metadata:
  name: stooges-curly
  labels:
    run: stooges-curly
spec:
  ports:
  - port: 6001
    protocol: TCP
    name: curly
    nodePort: 32001
  selector:
    run: stooges-curly
  type: NodePort
---
apiVersion: v1
kind: Service
metadata:
  name: stooges-larry
  labels:
    run: stooges-larry
spec:
  ports:
  - port: 6002
    protocol: TCP
    name: larry
    nodePort: 32002
  selector:
    run: stooges-larry
  type: NodePort
---
apiVersion: v1
kind: Service
metadata:
  name: stooges-moe
  labels:
    run: stooges-moe
spec:
  ports:
  - port: 6003
    protocol: TCP
    name: moe
    nodePort: 32003
  selector:
    run: stooges-moe
  type: NodePort
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: stooges-curly
spec:
  replicas: 1
  template:
    metadata:
      labels:
        run: stooges-curly
        stooge: curly
    spec:
      containers:
      - name: stooge-curly
        image: cdaringe/stooge:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 6001
        - containerPort: 6002
        - containerPort: 6003
        env:
        - name: STOOGE
          value: curly
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: stooges-larry
spec:
  replicas: 1
  template:
    metadata:
      labels:
        run: stooges-larry
        stooge: larry
    spec:
      containers:
      - name: stooge-larry
        image: cdaringe/stooge:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 6001
        - containerPort: 6002
        - containerPort: 6003
        env:
        - name: STOOGE
          value: larry
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: stooges-moe
spec:
  replicas: 1
  template:
    metadata:
      labels:
        run: stooges-moe
        stooge: moe
    spec:
      containers:
      - name: stooge-moe
        image: cdaringe/stooge:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 6001
        - containerPort: 6002
        - containerPort: 6003
        env:
        - name: STOOGE
          value: moe
